CUDA_VISIBLE_DEVICES=3,4 python -m torch.distributed.launch \
    --nproc_per_node=2 train_triplet.py \
    --data_folder ../../data/small_tagdc/final_data \
    --output_dir ../../data/tagdc_small_results \
    --vocab_file ../../data/small_tagdc/small_tagdc_commonTags.csv \
    --per_gpu_train_batch_size 4 \
    --logging_steps 100 \
    --gradient_accumulation_steps 8 \
    --num_train_epochs 3 \
    --fp16 \
    --fp16_opt_level O2 \
    --learning_rate 3e-5  2>&1| tee train_tagdc_small-fpO2.log