CUDA_VISIBLE_DEVICES=4,5 python -m torch.distributed.launch \
    --nproc_per_node=2 train_triplet.py \
    --data_folder ../../data/small_tagdc/final_data/train \
    --output_dir ../../data/tagdc_small_results \
    --train_numbers 38032 \
    --vocab_file ../../data/small_tagdc/small_tagdc_commonTags.csv \
    --per_gpu_train_batch_size 8 \
    --per_gpu_evalute_batch_size 4 \
    --logging_steps 100 \
    --gradient_accumulation_steps 2 \
    --num_train_epochs 500 \
    --fp16 \
    --fp16_opt_level O2 \
    --learning_rate 7e-5  2>&1| tee train_tagdc_small-fpO2.log